<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-83CVAPJ" name="bioApplication.RunBioEnroll" tests="4" failures="0" timestamp="08 Aug 2019 07:25:48 GMT" time="10.046" errors="3">
  <testcase name="loginBioEnroll" time="3.220" classname="bioApplication.RunBioEnroll">
    <error type="org.sikuli.script.FindFailed" message="Image/username.jpg: (222x43) in S(0)[0,0 1920x1080] E:Y, T:3.0">
      <![CDATA[FindFailed: Image/username.jpg: (222x43) in S(0)[0,0 1920x1080] E:Y, T:3.0  Line 2782, in file Region.javaat org.sikuli.script.Region.wait(Region.java:2782)at org.sikuli.script.Region.find(Region.java:2329)at org.sikuli.script.Region.getLocationFromTarget(Region.java:3238)at org.sikuli.script.Region.click(Region.java:3736)at org.sikuli.script.Region.click(Region.java:3721)at bioApplication.LoginBioEnroll.Login(LoginBioEnroll.java:23)at bioApplication.RunBioEnroll.loginBioEnroll(RunBioEnroll.java:47)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at bioApplication.MainApplication.main(MainApplication.java:16)]]>
    </error>
  </testcase> <!-- loginBioEnroll -->
  <testcase name="selectMainTask" time="0.753" classname="bioApplication.RunBioEnroll"/>
  <testcase name="saveDraft" time="3.054" classname="bioApplication.RunBioEnroll">
    <error type="org.sikuli.script.FindFailed" message="Image/card_type.jpg: (184x42) in S(0)[0,0 1920x1080] E:Y, T:3.0">
      <![CDATA[FindFailed: Image/card_type.jpg: (184x42) in S(0)[0,0 1920x1080] E:Y, T:3.0  Line 2782, in file Region.javaat org.sikuli.script.Region.wait(Region.java:2782)at org.sikuli.script.Region.find(Region.java:2329)at org.sikuli.script.Region.getLocationFromTarget(Region.java:3238)at org.sikuli.script.Region.click(Region.java:3736)at org.sikuli.script.Region.click(Region.java:3721)at bioApplication.TaskSelection.selectTask(TaskSelection.java:33)at bioApplication.RunBioEnroll.saveDraft(RunBioEnroll.java:63)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at bioApplication.MainApplication.main(MainApplication.java:16)]]>
    </error>
  </testcase> <!-- saveDraft -->
  <testcase name="saveDraft" time="3.019" classname="bioApplication.RunBioEnroll">
    <error type="org.sikuli.script.FindFailed" message="Image/card_type.jpg: (184x42) in S(0)[0,0 1920x1080] E:Y, T:3.0">
      <![CDATA[FindFailed: Image/card_type.jpg: (184x42) in S(0)[0,0 1920x1080] E:Y, T:3.0  Line 2782, in file Region.javaat org.sikuli.script.Region.wait(Region.java:2782)at org.sikuli.script.Region.find(Region.java:2329)at org.sikuli.script.Region.getLocationFromTarget(Region.java:3238)at org.sikuli.script.Region.click(Region.java:3736)at org.sikuli.script.Region.click(Region.java:3721)at bioApplication.TaskSelection.selectTask(TaskSelection.java:33)at bioApplication.RunBioEnroll.saveDraft(RunBioEnroll.java:63)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at bioApplication.MainApplication.main(MainApplication.java:16)]]>
    </error>
  </testcase> <!-- saveDraft -->
</testsuite> <!-- bioApplication.RunBioEnroll -->
